# Numpy

Date: 12/04/2022

Aim: To familiarize with numpy arrays and built in methods provided.

1. Create a numpy array using a list of ten items.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


2. Create a numpy arrays with different dimentions.

    ◦ Print the dimentions.
    
    ◦ Access the elements from the arrays.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c = np.array([[[1, 2, 3], [2, 5, 8]], [[4, 5, 6], [2, 3, 5]]])
print("Dimention of a" , a.ndim)
print("Dimention of b" ,b.ndim)
print("Dimention of c" ,c.ndim)

print("\nb[2][1] =", b[2][1])
print("c[0][0][2] =", c[0][0][2])

Dimention of a 1
Dimention of b 2
Dimention of c 3

b[2][1] = 8
c[0][0][2] = 3


3. Perform addition, multiplication and subtraction operations over any created numpy arrays.

In [ ]:
print(a+5)
print(a-10)
print(a/2)
print(a*3)

[ 6  7  8  9 10 11]
[-9 -8 -7 -6 -5 -4]
[0.5 1.  1.5 2.  2.5 3. ]
[ 3  6  9 12 15 18]


4. Discuss about arrange function in numpy with two examples.

    The Numpy arange function generates a NumPy array with evenly spaced values based on the start and stops intervals specified upon declaration.

    numpy.arange(
             [start],
              stop,
             [step],
             dtype=None
            )

In [ ]:
a = np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(1,80,9,dtype = "float")
print(a)

[ 1. 10. 19. 28. 37. 46. 55. 64. 73.]


5. Create a numpy array and perform square root and standard deviation on it.

In [ ]:
d = np.array([12, 23, 11, 23, 14, 15, 36])
SD = np.std(d)
SQRT = np.sqrt(d)
print("Square roots :", SQRT)
print("Stadard Deviation:",SD)

Square roots : [3.46410162 4.79583152 3.31662479 4.79583152 3.74165739 3.87298335
 6.        ]
Stadard Deviation: 8.236305888799757


6. Build a 2-dimentional array and perform 

    ◦ column sum
    
    ◦ row sum
    
    ◦ column mean
    
    ◦ row mean

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Row sums:")
for i in b:
    print( np.sum(i))

print("\nRow Mean:")
for i in b:
    print( np.mean(i))
    
b = np.transpose(b)

print("\nColumn sums:")
for i in b:
    print( np.sum(i))

print("\nColumn Mean:")
for i in b:
    print( np.mean(i))
    
b = np.transpose(b)

Row sums:
6
15
24

Row Mean:
2.0
5.0
8.0

Column sums:
12
15
18

Column Mean:
4.0
5.0
6.0


7. Generate arrays of zeros and ones with shape of (2,4).

In [ ]:
f = np.zeros((2, 4))
print(f)
print("\n")
g = np.ones((2, 4))
print(g)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


8. Create two numpy arrays and append data horizontally and vertically.

In [ ]:
h  = np.array([[1,2],[8,9]])
i = np.array([4, 5, 6])

j = np.vstack((h, i[:-1]))
print(j)

k = np.hstack((j, i[:, None]))
print("\n", k)

[[1 2]
 [8 9]
 [4 5]]

 [[1 2 4]
 [8 9 5]
 [4 5 6]]


9. Build two numpy array and perform the following
    
    ◦ search for an element in the array.
    
    ◦ Join the two arrays.
    
    ◦ Sort the elements in the array
    
    ◦ Broadcast the value 10 in 1 to 5 array index positions.

In [ ]:
l = np.array([12, 23, 11, 23, 14, 15, 36])
m = np.array([9, 10, 45, 3, 2, 20])
x= 14
i = np.where(l==x)
print(x, "found at {}".format(i[0]))

n = np.append(l,m)
print("\nJoined array:", n)

n = np.sort(n)
print("\nSorted array:", n)

n[1:5]=10
print("\nAfter Broadcast:", n)

14 found at [4]

Joined array: [12 23 11 23 14 15 36  9 10 45  3  2 20]

Sorted array: [ 2  3  9 10 11 12 14 15 20 23 23 36 45]

After Broadcast: [ 2 10 10 10 10 12 14 15 20 23 23 36 45]


10. Generate
  
  ◦ one dimentional array with 5 random integers from 10 to 50
  
  ◦ two dimetional array with 4 rows, each row containing 3 random integers from 5 to 10

In [ ]:
from numpy import random
x=random.randint(10, 50, size=(6))
print(x)

[47 29 15 41 14 18]


In [ ]:
x=random.randint(5, 10, size=(4,3))
print(x)

[[5 8 6]
 [6 5 9]
 [8 8 9]
 [9 5 7]]
